controllers/ContactManualController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Contact;
use app\models\ContactSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use \yii\web\Response;
use yii\helpers\Html;
use yii\data\Pagination;

class ContactManualController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                    'update' => ['post'],
                    'create' => ['post'],
                ],
            ],
        ];
    }

    public function actionIndex()
    {
        $query = Contact::find();

        $pagination = new Pagination([
            'defaultPageSize' => 10,
            'totalCount' => $query->count(),
        ]);

        $сontacts = $query->orderBy('id DESC')
            ->offset($pagination->offset)
            ->limit($pagination->limit)
            ->all();

        return $this->render('index', [
            'сontacts' => $сontacts,
            'pagination' => $pagination,
        ]);
    }


    public function actionCreate()
    {
        $request = Yii::$app->request;
        $model = new Contact();
        if ($request->isAjax) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            if ($model->load($request->post()) && $model->save()) {
                return [
                    'status' => 'success',
                    'contacts' => $this->findAll()
                ];
            } else {
                return [
                    'status' => 'error',
                    'model' => $model->getErrors(),
                ];
            }
        }
    }


    public function actionUpdate($id)
    {
        $request = Yii::$app->request;
        $model = $this->findModel($id);

        if ($request->isAjax) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            if ($model->load($request->post()) && $model->save()) {
                return [
                    'status' => 'success',
                    'contacts' => $this->findAll()
                ];
            } else {
                return [
                    'status' => 'error',
                    'model' => $model->getErrors(),
                ];
            }
        }
    }


    public function actionDelete($id)
    {
        $request = Yii::$app->request;
        $this->findModel($id)->delete();

        if ($request->isAjax) {

            Yii::$app->response->format = Response::FORMAT_JSON;
            return [
                'status' => 'success'
            ];
        }
    }


    protected function findAll()
    {
        $query = Contact::find();

        $pagination = new Pagination([
            'defaultPageSize' => 10,
            'totalCount' => $query->count(),
        ]);

        $сontacts = $query->orderBy('id DESC')
            ->offset($pagination->offset)
            ->limit($pagination->limit)
            ->all();

        return $сontacts;
    }

    protected function findModel($id)
    {
        if (($model = Contact::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/contact-manual/index.php
<?php

use yii\helpers\Url;
use yii\bootstrap5\LinkPager;
?>
<button type="button" class="btn btn-primary mt-3 mb-3" data-bs-toggle="modal" data-bs-target="#modal-contact" data-bs-action="create" data-bs-url="<?= Url::to(['contact-manual/create']); ?>">Добавить новый контакт</button>
<table class="table">
    <thead class="table-dark">
        <tr>
            <th scope="col">ID</th>
            <th scope="col">ФИО</th>
            <th scope="col">Email</th>
            <th scope="col">Телефон</th>
            <th scope="col">Действия</th>
        </tr>
    </thead>
    <tbody id="table-contacts">
        <?php foreach ($сontacts as $сontact) : ?>
            <tr id="contact-id<?= \yii\helpers\Html::encode($сontact->id)  ?>">
                <td><?= \yii\helpers\Html::encode($сontact->id) ?></td>
                <td><?= \yii\helpers\Html::encode($сontact->fullName()) ?></td>
                <td><?= \yii\helpers\Html::encode($сontact->email) ?></td>
                <td><?= \yii\helpers\Html::encode($сontact->cellphone) ?></td>
                <td>
                    <button type="button" class="btn btn-primary" style="width: max-content;" data-bs-toggle="modal" data-bs-action="update" data-bs-id="<?= $сontact->id ?>" data-bs-lastname="<?= \yii\helpers\Html::encode($сontact->lastname) ?>" data-bs-firstname="<?= \yii\helpers\Html::encode($сontact->firstname) ?>" data-bs-middlename="<?= \yii\helpers\Html::encode($сontact->middlename) ?>" data-bs-email="<?= \yii\helpers\Html::encode($сontact->email) ?>" data-bs-cellphone="<?= \yii\helpers\Html::encode($сontact->cellphone) ?>" data-bs-status="<?= \yii\helpers\Html::encode($сontact->status) ?>" data-bs-url="<?= Url::to(['contact-manual/update', 'id' => $сontact->id]); ?>" data-bs-target="#modal-contact">Редактировать</button>
                    <button class="btn btn-danger" onclick="deleteRow('<?= Url::to(['contact-manual/delete', 'id' => $сontact->id]); ?>', '<?= $сontact->id ?>')">Удалить</button>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<?=
LinkPager::widget([
    'pagination' => $pagination,
]);
?>
<?= $this->render('modal-form') ?>

<script>
    let page = '<?= isset($_GET['page']) ? $_GET['page'] : 1 ?>';
</script>
<?php $this->registerJsFile("@web/js/contact.js", [
    'depends' => [
        \yii\web\JqueryAsset::className()
    ]
]); ?>

views/contact-manual/modal-form.php
<?php

use yii\helpers\Html;

?>
<div class="modal fade" id="modal-contact" tabindex="-1" aria-labelledby="modal-contact-label" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modal-contact-label">Создать новый контакт</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form method="post" id="contact-form">

                    <?= Html::hiddenInput(\Yii::$app->getRequest()->csrfParam, \Yii::$app->getRequest()->getCsrfToken(), []); ?>
                    <input type="hidden" id="contact-id" name="Contact[id]">

                    <div class="mb-3 field-contact-lastname">
                        <label class="form-label" for="contact-lastname">Фамилия</label>
                        <input type="text" id="contact-lastname" class="form-control" name="Contact[lastname]" maxlength="32">
                        <div class="invalid-feedback"></div>
                    </div>
                    <div class="mb-3 field-contact-firstname">
                        <label class="form-label" for="contact-firstname">Имя</label>
                        <input type="text" id="contact-firstname" class="form-control" name="Contact[firstname]" maxlength="32">
                        <div class="invalid-feedback"></div>
                    </div>
                    <div class="mb-3 field-contact-middlename">
                        <label class="form-label" for="contact-middlename">Отчество</label>
                        <input type="text" id="contact-middlename" class="form-control" name="Contact[middlename]" maxlength="32">
                        <div class="invalid-feedback"></div>
                    </div>
                    <div class="mb-3 field-contact-email">
                        <label class="form-label" for="contact-email">Email</label>
                        <input type="text" id="contact-email" class="form-control" name="Contact[email]" maxlength="32">
                        <div class="invalid-feedback"></div>
                    </div>
                    <div class="mb-3 field-contact-cellphone">
                        <label class="form-label" for="contact-cellphone">Сотовый телефон</label>
                        <input type="text" id="contact-cellphone" class="form-control" name="Contact[cellphone]" maxlength="32">
                        <div class="invalid-feedback"></div>
                    </div>
                    <div class="mb-3 field-contact-status">
                        <label class="form-label" for="contact-status">Статус</label>
                        <select id="contact-status" class="form-select" name="Contact[status]">
                            <option value="1">Активен</option>
                            <option value="0">Удален</option>
                        </select>
                        <div class="invalid-feedback"></div>
                    </div>
                    <div class="d-flex justify-content-end">
                        <button id="modal-submit-button" type="submit" class="btn btn-primary">Сохранить</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>